.TH DSSH 1 "2016-02-21" "" "User Commands"
.SH NAME
.NM dssh
.ND Distributed SSH Tool
.SH SYNOPSIS
.B dssh
[-aAcpq]
[\-f\ host_file...]
[\-i\ id_file]
[\-l\ host-list...]
[\-o\ ssh_opts]
[\-u\ username]
[\-s\ timeout]
[-t\ max_threads]
.B command
.SH DESCRIPTION
...
.TP
.I "\-a"
.TP
.I "\-A"
.TP
.I "\-c"
.TP
.I "\-i" id_file
.TP
.I "\-o" ssh_opts
.TP
.I "\-p"
.TP
.I "\-q"
.TP
.I "\-u" username
.TP
.I "\-s" timeout
.TP
.I "\-t" num_threads
.SH AUTHOR
Matthew Malensek <matt@malensek.net>
.SH HOMEPAGE
http://matthew.malensek.net
.SH LICENSE
This software is released under the 2-Clause BSD License.  See LICENSE.txt file for details.
