.TH DSSH 1 "2016-02-21" "" "User Commands"
.SH NAME
.NM dssh
.ND Distributed SSH Tool
.\"--------------------------------------------------------------------------"/.
.SH SYNOPSIS
.B dssh
[-aAcpq]
[\-f\ host_file...]
[\-i\ id_file]
[\-l\ host-list...]
[\-o\ ssh_opts]
[\-u\ username]
[\-s\ timeout]
[-t\ max_threads]
.B command
.SH DESCRIPTION
.B dssh
is a simple utility for executing commands across several hosts via ssh.
Commands may be executed in parallel or sequentially, and a variety of
formatting and output options are supported.
.PP
Remote hosts for command execution are specified by file(s), lists on the
command line, or hostnames piped from standard input. Whitespace is used to
distinguish between hosts. A connection is made to each host via ssh and the
user-defined
.B command
is executed.
.PP
While the basic functionality provided by
.B dssh
can be mimicked with a few lines of shell script, additional features such as
limiting the number of active threads, output collection/formatting, and
colorization are supported.
.SH OPTIONS
.TP
.I "\-a"
.TP
.I "\-A"
.TP
.I "\-c"
.TP
.I "\-i"\ id_file
.TP
.I "\-o"\ ssh_opts
.TP
.I "\-p"
.TP
.I "\-q"
.TP
.I "\-u"\ username
.TP
.I "\-s"\ timeout
.TP
.I "\-t"\ num_threads
.TP
.I "\-y"
.SH EXIT STATUS
.SH ENVIRONMENT
DSSH_HOSTS variable
.SH AUTHOR
Matthew Malensek <matt@malensek.net>
.SH HOMEPAGE
http://matthew.malensek.net
.SH LICENSE
This software is released under the 2-Clause BSD License.  See LICENSE.txt file for details.
